title: Misja Pronk - Resume
baseURL: https://misja-pronk.github.io/resume/
languageCode: en-us
params:
  address: Pijlpunt 16 2496SN Den Haag Nederland
  email: misjapronk@hotmail.com
  favicon: favicon.ico
  firstName: Misja
  lastName: Pronk
  profileImage: img/profile-picture.webp
  handles:
    - link: www.linkedin.com/in/misja-pronk
      name: LinkedIn
    - link: https://github.com/misja-pronk
      name: GitHub
outputs:
  home:
    - HTML
    - JSON
taxonomies:
  tag: tags

